//
//  MyData.swift
//  HelloTrip
//
//  Created by dong wook on 2017. 12. 19..
//  Copyright © 2017년 SSU. All rights reserved.
//

import Foundation

class MyData{

    let flags : [Flag] = [Flag(fullName:"안도라",changeName:"EUR",shortenName:"ad",exchangeRate:1),
                          Flag(fullName:"아랍에미리트",changeName:"AED",shortenName:"ae",exchangeRate:1),
                          Flag(fullName:"아프가니스탄",changeName:"AFN",shortenName:"af",exchangeRate:1),
                          Flag(fullName:"앙골라",changeName:"KZT",shortenName:"ao",exchangeRate:1),
                          Flag(fullName:"아르헨티나",changeName:"ARS",shortenName:"ar",exchangeRate:1),
                          Flag(fullName:"오스트리아",changeName:"EUR",shortenName:"at",exchangeRate:1),
                          Flag(fullName:"호주",changeName:"AUD",shortenName:"au",exchangeRate:1),
                          Flag(fullName:"아제르바이잔",changeName:"AZN",shortenName:"az",exchangeRate:1),
                          Flag(fullName:"방글라데시",changeName:"BDT",shortenName:"bd",exchangeRate:1),
                          Flag(fullName:"벨기에",changeName:"EUR",shortenName:"be",exchangeRate:1),
                          Flag(fullName:"방글라데시",changeName:"BDT",shortenName:"bd",exchangeRate:1),
                          Flag(fullName:"불가리아",changeName:"EUR",shortenName:"bg",exchangeRate:1),
                          Flag(fullName:"바레인",changeName:"BHD",shortenName:"bh",exchangeRate:1),
                          Flag(fullName:"브루나이",changeName:"BND",shortenName:"bn",exchangeRate:1),
                          Flag(fullName:"볼리비아",changeName:"BOB",shortenName:"bo",exchangeRate:1),
                          Flag(fullName:"브라질",changeName:"BRL",shortenName:"br",exchangeRate:1),
                          Flag(fullName:"바하마",changeName:"USD",shortenName:"bs",exchangeRate:1),
                          Flag(fullName:"캐나다",changeName:"CAD",shortenName:"ca",exchangeRate:1),
                          Flag(fullName:"중앙아프리카",changeName:"XAF",shortenName:"cf",exchangeRate:1),
                          Flag(fullName:"스위스",changeName:"CHF",shortenName:"ch",exchangeRate:1),
                          Flag(fullName:"코트디부와르",changeName:"XOF",shortenName:"ci",exchangeRate:1),
                          Flag(fullName:"칠레",changeName:"CLP",shortenName:"cl",exchangeRate:1),
                          Flag(fullName:"중국",changeName:"CNY",shortenName:"cn",exchangeRate:1),
                          Flag(fullName:"콜롬비아",changeName:"COP",shortenName:"co",exchangeRate:1),
                          Flag(fullName:"코스타리카",changeName:"CRC",shortenName:"cr",exchangeRate:1),
                          Flag(fullName:"쿠바",changeName:"CUP",shortenName:"cu",exchangeRate:1),
                          Flag(fullName:"체코",changeName:"CZK",shortenName:"cz",exchangeRate:1),
                          Flag(fullName:"독일",changeName:"EUR",shortenName:"de",exchangeRate:1),
                          Flag(fullName:"덴마크",changeName:"DKK",shortenName:"dk",exchangeRate:1),
                          Flag(fullName:"도미니카 공화국",changeName:"DOP",shortenName:"do",exchangeRate:1),
                          Flag(fullName:"알제리",changeName:"DZD",shortenName:"dz",exchangeRate:1),
                          Flag(fullName:"에콰도르",changeName:"USD",shortenName:"ec",exchangeRate:1),
                          Flag(fullName:"에스토니아",changeName:"EUR",shortenName:"ee",exchangeRate:1),
                          Flag(fullName:"이집트",changeName:"EGP",shortenName:"eg",exchangeRate:1),
                          Flag(fullName:"스페인",changeName:"EUR",shortenName:"es",exchangeRate:1),
                          Flag(fullName:"이디오피아",changeName:"ETB",shortenName:"et",exchangeRate:1),
                          Flag(fullName:"핀란드",changeName:"EUR",shortenName:"fi",exchangeRate:1),
                          Flag(fullName:"피지",changeName:"PJD",shortenName:"fj",exchangeRate:1),
                          Flag(fullName:"프랑스",changeName:"EUR",shortenName:"fr",exchangeRate:1),
                          Flag(fullName:"영국",changeName:"GBP",shortenName:"gb",exchangeRate:1),
                          Flag(fullName:"그루지아",changeName:"GEL",shortenName:"ge",exchangeRate:1),
                          Flag(fullName:"가나",changeName:"GHS",shortenName:"gh",exchangeRate:1),
                          Flag(fullName:"감비아",changeName:"ZMW",shortenName:"gm",exchangeRate:1),
                          Flag(fullName:"기니",changeName:"GNF",shortenName:"gn",exchangeRate:1),
                          Flag(fullName:"그리스",changeName:"EUR",shortenName:"gr",exchangeRate:1),
                          Flag(fullName:"과테말라",changeName:"GTQ",shortenName:"gt",exchangeRate:1),
                          Flag(fullName:"온두라스",changeName:"HNL",shortenName:"hn",exchangeRate:1),
                          Flag(fullName:"크로아티아",changeName:"HRK",shortenName:"hr",exchangeRate:1),
                          Flag(fullName:"아이티",changeName:"HTG",shortenName:"ht",exchangeRate:1),
                          Flag(fullName:"헝가리",changeName:"HUF",shortenName:"hu",exchangeRate:1),
                          Flag(fullName:"인도네시아",changeName:"IDR",shortenName:"id",exchangeRate:1),
                          Flag(fullName:"아일랜드",changeName:"EUR",shortenName:"ie",exchangeRate:1),
                          Flag(fullName:"이스라엘",changeName:"ILS",shortenName:"il",exchangeRate:1),
                          Flag(fullName:"인도",changeName:"INR",shortenName:"in",exchangeRate:1),
                          Flag(fullName:"이라크",changeName:"IQD",shortenName:"iq",exchangeRate:1),
                          Flag(fullName:"이란",changeName:"IRR",shortenName:"ir",exchangeRate:1),
                          Flag(fullName:"아이슬란드",changeName:"IRR",shortenName:"is",exchangeRate:1),
                          Flag(fullName:"이탈리아",changeName:"EUR",shortenName:"it",exchangeRate:1),
                          Flag(fullName:"자메이카",changeName:"JMD",shortenName:"jm",exchangeRate:1),
                          Flag(fullName:"요르단",changeName:"JOD",shortenName:"jo",exchangeRate:1),
                          Flag(fullName:"일본",changeName:"JPY",shortenName:"jp",exchangeRate:1),
                          Flag(fullName:"케냐",changeName:"KES",shortenName:"ke",exchangeRate:1),
                          Flag(fullName:"키르기스스탄",changeName:"KGS",shortenName:"kg",exchangeRate:1),
                          Flag(fullName:"캄보디아",changeName:"KHR",shortenName:"kh",exchangeRate:1),
                          Flag(fullName:"키리바시",changeName:"AUD",shortenName:"ki",exchangeRate:1),
                          Flag(fullName:"코모르",changeName:"KMF",shortenName:"km",exchangeRate:1),
                          Flag(fullName:"대한민국",changeName:"KRW",shortenName:"kr",exchangeRate:1),
                          Flag(fullName:"쿠웨이트",changeName:"KWD",shortenName:"kw",exchangeRate:1),
                          Flag(fullName:"카자흐스탄",changeName:"KZT",shortenName:"kz",exchangeRate:1),
                          Flag(fullName:"라오스",changeName:"LAK",shortenName:"la",exchangeRate:1),
                          Flag(fullName:"레바논",changeName:"LBP",shortenName:"lb",exchangeRate:1),
                          Flag(fullName:"세인트 루시아",changeName:"XCD",shortenName:"lc",exchangeRate:1),
                          Flag(fullName:"리히텐슈타인",changeName:"CHF",shortenName:"li",exchangeRate:1),
                          Flag(fullName:"스리랑카",changeName:"LKR",shortenName:"lk",exchangeRate:1),
                          Flag(fullName:"라이베리아",changeName:"LRD",shortenName:"lr",exchangeRate:1),
                          Flag(fullName:"스리랑카",changeName:"LSL",shortenName:"ls",exchangeRate:1),
                          Flag(fullName:"룩셈부르크",changeName:"EUR",shortenName:"lu",exchangeRate:1),
                          Flag(fullName:"라트비아",changeName:"EUR",shortenName:"lv",exchangeRate:1),
                          Flag(fullName:"리비아",changeName:"EUR",shortenName:"ly",exchangeRate:1),
                          Flag(fullName:"모로코",changeName:"MAD",shortenName:"ma",exchangeRate:1),
                          Flag(fullName:"모나코",changeName:"EUR",shortenName:"mc",exchangeRate:1),
                          Flag(fullName:"몰도바",changeName:"MDL",shortenName:"md",exchangeRate:1),
                          Flag(fullName:"마다가스카르",changeName:"MGA",shortenName:"mg",exchangeRate:1),
                          Flag(fullName:"미얀마",changeName:"MMK",shortenName:"mm",exchangeRate:1),
                          Flag(fullName:"몽골",changeName:"MNT",shortenName:"mn",exchangeRate:1),
                          Flag(fullName:"모리셔스",changeName:"MUR",shortenName:"mu",exchangeRate:1),
                          Flag(fullName:"몰디브",changeName:"MVR",shortenName:"mv",exchangeRate:1),
                          Flag(fullName:"말라위",changeName:"MWK",shortenName:"mw",exchangeRate:1),
                          Flag(fullName:"멕시코",changeName:"MXN",shortenName:"mx",exchangeRate:1),
                          Flag(fullName:"말레이시아",changeName:"MYR",shortenName:"my",exchangeRate:1),
                          Flag(fullName:"모잠비크",changeName:"MZN",shortenName:"mz",exchangeRate:1),
                          Flag(fullName:"나미비아",changeName:"NAD",shortenName:"na",exchangeRate:1),
                          Flag(fullName:"니제르",changeName:"NGN",shortenName:"ne",exchangeRate:1),
                          Flag(fullName:"나이지리아",changeName:"NGN",shortenName:"ng",exchangeRate:1),
                          Flag(fullName:"니카라과",changeName:"NIO",shortenName:"ni",exchangeRate:1),
                          Flag(fullName:"네덜란드",changeName:"ANG",shortenName:"nl",exchangeRate:1),
                          Flag(fullName:"노르웨이",changeName:"NOK",shortenName:"no",exchangeRate:1),
                          Flag(fullName:"네팔",changeName:"NPR",shortenName:"np",exchangeRate:1),
                          Flag(fullName:"오만",changeName:"OMR",shortenName:"om",exchangeRate:1),
                          Flag(fullName:"파나마",changeName:"PAB",shortenName:"pa",exchangeRate:1),
                          Flag(fullName:"페루",changeName:"PEN",shortenName:"pe",exchangeRate:1),
                          Flag(fullName:"파프아뉴기니",changeName:"PGK",shortenName:"pg",exchangeRate:1),
                          Flag(fullName:"필리핀",changeName:"PHP",shortenName:"ph",exchangeRate:1),
                          Flag(fullName:"파키스탄",changeName:"PKR",shortenName:"pk",exchangeRate:1),
                          Flag(fullName:"폴란드",changeName:"PLN",shortenName:"pl",exchangeRate:1),
                          Flag(fullName:"포르투갈",changeName:"EUR",shortenName:"pt",exchangeRate:1),
                          Flag(fullName:"팔라우",changeName:"USD",shortenName:"pw",exchangeRate:1),
                          Flag(fullName:"파라과이",changeName:"PYG",shortenName:"py",exchangeRate:1),
                          Flag(fullName:"카타르",changeName:"QAR",shortenName:"qa",exchangeRate:1),
                          Flag(fullName:"루마니아",changeName:"RON",shortenName:"ro",exchangeRate:1),
                          Flag(fullName:"러시아",changeName:"RUB",shortenName:"ru",exchangeRate:1),
                          Flag(fullName:"르완다",changeName:"RWF",shortenName:"rw",exchangeRate:1),
                          Flag(fullName:"사우디아라비아",changeName:"SAR",shortenName:"sa",exchangeRate:1),
                          Flag(fullName:"세이셸",changeName:"SCR",shortenName:"sc",exchangeRate:1),
                          Flag(fullName:"수단",changeName:"SDG",shortenName:"sd",exchangeRate:1),
                          Flag(fullName:"스웨덴",changeName:"SEK",shortenName:"se",exchangeRate:1),
                          Flag(fullName:"싱가폴",changeName:"SGD",shortenName:"sg",exchangeRate:1),
                          Flag(fullName:"슬로베니아",changeName:"EUR",shortenName:"si",exchangeRate:1),
                          Flag(fullName:"슬로바키아",changeName:"EUR",shortenName:"sk",exchangeRate:1),
                          Flag(fullName:"시에라리온",changeName:"SLL",shortenName:"sl",exchangeRate:1),
                          Flag(fullName:"산마리노",changeName:"EUR",shortenName:"sm",exchangeRate:1),
                          Flag(fullName:"소말리아",changeName:"SOS",shortenName:"so",exchangeRate:1),
                          Flag(fullName:"수리남",changeName:"SRD",shortenName:"sr",exchangeRate:1),
                          Flag(fullName:"엘살바도르",changeName:"USD",shortenName:"sv",exchangeRate:1),
                          Flag(fullName:"시리아",changeName:"SYP",shortenName:"sy",exchangeRate:1),
                          Flag(fullName:"스와질랜드",changeName:"SZL",shortenName:"sz",exchangeRate:1),
                          Flag(fullName:"태국",changeName:"THB",shortenName:"th",exchangeRate:1),
                          Flag(fullName:"타지키스탄",changeName:"TJS",shortenName:"tj",exchangeRate:1),
                          Flag(fullName:"투르크메니스탄",changeName:"TMT",shortenName:"tm",exchangeRate:1),
                          Flag(fullName:"튀니지",changeName:"TND",shortenName:"tn",exchangeRate:1),
                          Flag(fullName:"통가",changeName:"TOP",shortenName:"to",exchangeRate:1),
                          Flag(fullName:"터키",changeName:"TRY",shortenName:"tr",exchangeRate:1),
                          Flag(fullName:"트리니다드 토바고",changeName:"TTD",shortenName:"tt",exchangeRate:1),
                          Flag(fullName:"대만",changeName:"TWD",shortenName:"tw",exchangeRate:1),
                          Flag(fullName:"탄자니아",changeName:"TZS",shortenName:"tz",exchangeRate:1),
                          Flag(fullName:"우크라이나",changeName:"UAH",shortenName:"ua",exchangeRate:1),
                          Flag(fullName:"우간다",changeName:"UGX",shortenName:"ug",exchangeRate:1),
                          Flag(fullName:"미국",changeName:"USD",shortenName:"us",exchangeRate:1),
                          Flag(fullName:"우루과이",changeName:"UYU",shortenName:"uy",exchangeRate:1),
                          Flag(fullName:"우즈베키스탄",changeName:"UZS",shortenName:"uz",exchangeRate:1),
                          Flag(fullName:"바티칸",changeName:"EUR",shortenName:"va",exchangeRate:1),
                          Flag(fullName:"베네수엘라",changeName:"VEF",shortenName:"ve",exchangeRate:1),
                          Flag(fullName:"베트남",changeName:"VND",shortenName:"vn",exchangeRate:1),
                          Flag(fullName:"바누아투",changeName:"VUV",shortenName:"vu",exchangeRate:1),
                          Flag(fullName:"사모아",changeName:"WST",shortenName:"ws",exchangeRate:1),
                          Flag(fullName:"예맨",changeName:"YER",shortenName:"ye",exchangeRate:1),
                          Flag(fullName:"남아프리카",changeName:"ZAR",shortenName:"za",exchangeRate:1)]
    
    
    class var Container : MyData{
        struct Static{
            static let flags = MyData()
        }
        return Static.flags
    }
    
}
