# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'HelloTrip' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
 use_frameworks!
 pod "Floaty", "~> 3.0.0" # Use version 4.0.0 for Swift 4.0
 pod 'GoogleMaps'
 pod 'GooglePlaces'
 pod 'FSCalendar'
 pod 'SSCalendar', '~> 0.0'
 pod 'SideMenu'
# Pods for HelloTrip

end
